services:
  python:
    build: .
    ports:
      - "3333:5000"
    volumes:
      - .:/usr/src/app
  adminer:
    image: adminer
    ports:
      - 8080:8080
  db:
    volumes:
      - db:/var/lib/myqsl
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: heslo

volumes:
  db:

